# Generated by Django 3.2.12 on 2022-08-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=11)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=4)),
                ('fecha_ini', models.DateField(verbose_name='Inicio Ciclo Lectivo')),
                ('fecha_fin', models.DateField(verbose_name='Fin Ciclo Lectivo')),
            ],
            options={
                'verbose_name_plural': 'Ciclo Lectivo',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_text', models.CharField(max_length=80)),
                ('cicloLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.ciclolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_de_cursado', models.CharField(max_length=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primTrim', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('seguTrim', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('tercTrim', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cuarTrim', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.asignatura')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.ficha')),
            ],
        ),
    ]
