# Generated by Django 3.2.12 on 2022-09-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
