# Generated by Django 3.2.12 on 2022-08-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20220829_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cicloLectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.ciclolectivo', verbose_name='Ciclo Lectivo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='cuarTrim',
            field=models.FloatField(blank=True, null=True, verbose_name='Cuarto Trimestre'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='primTrim',
            field=models.FloatField(blank=True, null=True, verbose_name='Primer Trimestre'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='seguTrim',
            field=models.FloatField(blank=True, null=True, verbose_name='Segundo Trimestre'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tercTrim',
            field=models.FloatField(blank=True, null=True, verbose_name='Tercer Trimestre'),
        ),
    ]
